conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random-outpainting
    mask_prob_dist: !!python/tuple [0, .32]  # for random
    image_size: 384


  noise:
    name: gaussian
    sigma: 0.05
