data:
  name: PASCAL VOC 
  image_path: ./Datasets/Pascal_VOC/VOC2012/JPEGImages
  label_path: ./Datasets/Pascal_VOC/VOC2012/Annotations
  save_path: ./Datasets/Pascal_VOC/SYN_VOC2012
  ext: xml

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: entire 
    mask_param:
      method: gaussian
      distribution: !!python/tuple [0, 0.4]  # Mu and Sigma
      margin: !!python/tuple [16,16] # Width and Height Margin 
  noise:
    name: gaussian
    sigma: 0.05
